KenakataApp/KenakataApp/Models/AdminLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace KenakataApp.Models
{
    public class AdminLogin
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage="Please enter user name")]
        [Display(Name="User Name")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Please enter password")]
        [DataType(DataType.Password)]
        [StringLength(50,MinimumLength=6,ErrorMessage="Password must be 6-10 characters")]
        public string Password { get; set; }

    }
}

KenakataApp/KenakataApp/Controllers/AdminLoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KenakataApp.Models;
using System.Web.Security;

namespace KenakataApp.Controllers
{
    public class AdminLoginController : Controller
    {
        private DiscountDbContext db = new DiscountDbContext();


        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(AdminLogin admin)
        {
            //string pass = FormsAuthentication.HashPasswordForStoringInConfigFile(admin.Password, "SHA1");
            //if (ModelState.IsValid)
            //{
            //     //admin.Password = pass;
            //    //var user = db.AdminLogin.Where(x => x.UserName == admin.UserName && x.Password == admin.Password).Count();
            //    //if (user == 0)
            //    //{
            //    //    ViewBag.forgot = "forgot password?";
            //    //    ViewBag.msg = "Username and/or password not match.";
            //        return View();
            //    //}
            //    //else
            //    //{
            //    //    FormsAuthentication.SetAuthCookie(admin.UserName, false);
            //    //    return RedirectToAction("Index", "Discount");
                   
            //    //}

            //}
            Api.AdminLoginController adminLogin=new Api.AdminLoginController();
            adminLogin.GetAdminLogin(1);
            return View();
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

    }
}

KenakataApp/KenakataApp/Controllers/Api/AdminLoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Mvc;
using KenakataApp.Models;

namespace KenakataApp.Controllers.Api
{
    public class AdminLoginController : ApiController
    {
        private DiscountDbContext db = new DiscountDbContext();

        //// GET api/AdminLogin

        //[OutputCache(Duration = 100)]
        //public IQueryable<AdminLogin> GetAdminLogin()
        //{
            
        //    return db.AdminLogin;
        //}

        // GET api/AdminLogin/5
        [ResponseType(typeof(AdminLogin))]
        public IHttpActionResult GetAdminLogin(int id)
        {
            Controllers.AdminLoginController adminLoginController=new Controllers.AdminLoginController();
            AdminLogin adminlogin = db.AdminLogin.Find();

            //if (adminlogin == null)
            //{
            //    return NotFound();
            //}
                
            //else
            //{
            //} 
            var user = db.AdminLogin.Where(x => x.UserName == adminlogin.UserName && x.Password == adminlogin.Password).Count();
            if (user == 1)
            {
                adminLoginController.ViewBag.forget = "Not found";
                adminLoginController.Response.Redirect("http://www.kenakatabd.somee.com/discount/create#");
            }
            return NotFound();
        }

       

        // PUT api/AdminLogin/5
        public IHttpActionResult PutAdminLogin(int id, AdminLogin adminlogin)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != adminlogin.Id)
            {
                return BadRequest();
            }

            db.Entry(adminlogin).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AdminLoginExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST api/AdminLogin
        [ResponseType(typeof(AdminLogin))]
        public IHttpActionResult PostAdminLogin(AdminLogin adminlogin)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.AdminLogin.Add(adminlogin);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = adminlogin.Id }, adminlogin);
        }

        // DELETE api/AdminLogin/5
        [ResponseType(typeof(AdminLogin))]
        public IHttpActionResult DeleteAdminLogin(int id)
        {
            AdminLogin adminlogin = db.AdminLogin.Find(id);
            if (adminlogin == null)
            {
                return NotFound();
            }

            db.AdminLogin.Remove(adminlogin);
            db.SaveChanges();

            return Ok(adminlogin);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool AdminLoginExists(int id)
        {
            return db.AdminLogin.Count(e => e.Id == id) > 0;
        }
    }
}

KenakataApp/KenakataApp/Views/AdminLogin/Login.cshtml
@model KenakataApp.Models.AdminLogin

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Login", "AdminLogin", FormMethod.Post, new { id = "saveLoginForm" }))
{
   @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <div class="form-group">

            @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName)
                @Html.ValidationMessageFor(model => model.UserName)

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)

            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-primary" />
                <br />
                <span style="font-style:italic;color:red">@ViewBag.msg</span>
            </div>

        </div>

    </div>
}
@section Scripts {

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script>
        $("#saveLoginForm").validate({
            rules: {
                UserName: "required",
                Password: {
                    required: true,
                    maxlength: 20,
                    minlength: 6
                },

            },
            messages: {
                UserName: "Please enter user name",
                Password: {
                    required: "Please enter the password",
                    maxlength: "Password must consist of at most 10 characters",
                    minlength: "Password must consist of at least 6 characters"
                },

            }
        });
    </script>
}